---
name: Async-MergePoint
version: 0.03
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: resynchronise diverged control flow
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Async::MergePoint:
    file: lib/Async/MergePoint.pm
    version: 0.03
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
